/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as specialRouteRouteImport } from './routes/(special)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as specialOnboardingRouteImport } from './routes/(special)/onboarding'
import { Route as specialResetPasswordRouteImport } from './routes/(special)/reset-password'
import { Route as appCampaignsIndexRouteImport } from './routes/(app)/campaigns/index'
import { Route as appCampaignsIdRouteImport } from './routes/(app)/campaigns/$id'
import { Route as appCampaignsMyRouteImport } from './routes/(app)/campaigns/my'
import { Route as appCampaignsNewRouteImport } from './routes/(app)/campaigns/new'
import { Route as appSettingsChar123TabChar125RouteImport } from './routes/(app)/settings/{-$tab}'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const specialRouteRoute = specialRouteRouteImport.update({
  id: '/(special)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const specialOnboardingRoute = specialOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => specialRouteRoute,
} as any)
const specialResetPasswordRoute = specialResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => specialRouteRoute,
} as any)
const appCampaignsIndexRoute = appCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCampaignsIdRoute = appCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCampaignsMyRoute = appCampaignsMyRouteImport.update({
  id: '/campaigns/my',
  path: '/campaigns/my',
  getParentRoute: () => appRouteRoute,
} as any)
const appCampaignsNewRoute = appCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsChar123TabChar125Route =
  appSettingsChar123TabChar125RouteImport.update({
    id: '/settings/{-$tab}',
    path: '/settings/{-$tab}',
    getParentRoute: () => appRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/onboarding': typeof specialOnboardingRoute
  '/reset-password': typeof specialResetPasswordRoute
  '/': typeof appIndexRoute
  '/campaigns/$id': typeof appCampaignsIdRoute
  '/campaigns/my': typeof appCampaignsMyRoute
  '/campaigns/new': typeof appCampaignsNewRoute
  '/settings/{-$tab}': typeof appSettingsChar123TabChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/campaigns/': typeof appCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/onboarding': typeof specialOnboardingRoute
  '/reset-password': typeof specialResetPasswordRoute
  '/': typeof appIndexRoute
  '/campaigns/$id': typeof appCampaignsIdRoute
  '/campaigns/my': typeof appCampaignsMyRoute
  '/campaigns/new': typeof appCampaignsNewRoute
  '/settings/{-$tab}': typeof appSettingsChar123TabChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/campaigns': typeof appCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(special)': typeof specialRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(special)/onboarding': typeof specialOnboardingRoute
  '/(special)/reset-password': typeof specialResetPasswordRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/campaigns/$id': typeof appCampaignsIdRoute
  '/(app)/campaigns/my': typeof appCampaignsMyRoute
  '/(app)/campaigns/new': typeof appCampaignsNewRoute
  '/(app)/settings/{-$tab}': typeof appSettingsChar123TabChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(app)/campaigns/': typeof appCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/reset-password'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/my'
    | '/campaigns/new'
    | '/settings/{-$tab}'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/reset-password'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/my'
    | '/campaigns/new'
    | '/settings/{-$tab}'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/campaigns'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(special)'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(special)/onboarding'
    | '/(special)/reset-password'
    | '/(app)/'
    | '/(app)/campaigns/$id'
    | '/(app)/campaigns/my'
    | '/(app)/campaigns/new'
    | '/(app)/settings/{-$tab}'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(app)/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  specialRouteRoute: typeof specialRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(special)': {
      id: '/(special)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof specialRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(special)/onboarding': {
      id: '/(special)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof specialOnboardingRouteImport
      parentRoute: typeof specialRouteRoute
    }
    '/(special)/reset-password': {
      id: '/(special)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof specialResetPasswordRouteImport
      parentRoute: typeof specialRouteRoute
    }
    '/(app)/campaigns/': {
      id: '/(app)/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof appCampaignsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/campaigns/$id': {
      id: '/(app)/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof appCampaignsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/campaigns/my': {
      id: '/(app)/campaigns/my'
      path: '/campaigns/my'
      fullPath: '/campaigns/my'
      preLoaderRoute: typeof appCampaignsMyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/campaigns/new': {
      id: '/(app)/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof appCampaignsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/{-$tab}': {
      id: '/(app)/settings/{-$tab}'
      path: '/settings/{-$tab}'
      fullPath: '/settings/{-$tab}'
      preLoaderRoute: typeof appSettingsChar123TabChar125RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appCampaignsIdRoute: typeof appCampaignsIdRoute
  appCampaignsMyRoute: typeof appCampaignsMyRoute
  appCampaignsNewRoute: typeof appCampaignsNewRoute
  appSettingsChar123TabChar125Route: typeof appSettingsChar123TabChar125Route
  appCampaignsIndexRoute: typeof appCampaignsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appCampaignsIdRoute: appCampaignsIdRoute,
  appCampaignsMyRoute: appCampaignsMyRoute,
  appCampaignsNewRoute: appCampaignsNewRoute,
  appSettingsChar123TabChar125Route: appSettingsChar123TabChar125Route,
  appCampaignsIndexRoute: appCampaignsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface specialRouteRouteChildren {
  specialOnboardingRoute: typeof specialOnboardingRoute
  specialResetPasswordRoute: typeof specialResetPasswordRoute
}

const specialRouteRouteChildren: specialRouteRouteChildren = {
  specialOnboardingRoute: specialOnboardingRoute,
  specialResetPasswordRoute: specialResetPasswordRoute,
}

const specialRouteRouteWithChildren = specialRouteRoute._addFileChildren(
  specialRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  specialRouteRoute: specialRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
