BEGIN;

-- `currentItems` is nullable because it does not apply to virtual campaigns.
-- The old default populated virtual rows with a physical-only value.
ALTER TABLE "campaigns"
  ALTER COLUMN "currentItems" DROP DEFAULT;

UPDATE "campaigns"
SET "currentItems" = NULL
WHERE "type" = 'VIRTUAL'
  AND "currentItems" = 0;

ALTER TABLE "campaigns"
  ADD CONSTRAINT "campaigns_end_date_after_start_date_check"
    CHECK ("endDate" > "startDate"),
  ADD CONSTRAINT "campaigns_physical_fields_check"
    CHECK (
      "type" <> 'PHYSICAL'
      OR (
        NULLIF(BTRIM("location"), '') IS NOT NULL
        AND "targetItems" IS NOT NULL
        AND "targetItems" > 0
        AND "currentItems" IS NOT NULL
        AND "currentItems" >= 0
        AND "pixKey" IS NULL
        AND "bankAccountInfo" IS NULL
      )
    ),
  ADD CONSTRAINT "campaigns_virtual_fields_check"
    CHECK (
      "type" <> 'VIRTUAL'
      OR (
        "location" IS NULL
        AND "targetItems" IS NULL
        AND "currentItems" IS NULL
        AND (
          NULLIF(BTRIM("pixKey"), '') IS NOT NULL
          OR NULLIF(BTRIM("bankAccountInfo"), '') IS NOT NULL
        )
      )
    ),
  ADD CONSTRAINT "campaigns_lifecycle_timestamps_check"
    CHECK (
      ("status" IN ('PENDING', 'ACTIVE') AND "completedAt" IS NULL AND "cancelledAt" IS NULL)
      OR ("status" = 'COMPLETED' AND "completedAt" IS NOT NULL AND "cancelledAt" IS NULL)
      OR ("status" = 'CANCELLED' AND "completedAt" IS NULL AND "cancelledAt" IS NOT NULL)
    );

ALTER TABLE "campaign_accountabilities"
  ADD CONSTRAINT "campaign_accountabilities_total_items_nonnegative_check"
    CHECK ("totalItems" >= 0);

ALTER TABLE "organizer_profiles"
  ADD CONSTRAINT "organizer_profiles_type_cnpj_check"
    CHECK (
      ("type" = 'INDIVIDUAL' AND "cnpj" IS NULL AND "cnpjVerified" = false)
      OR (
        "type" = 'ORGANIZATION'
        AND "cnpj" IS NOT NULL
        AND "cnpj" ~ '^[0-9]{14}$'
      )
    );

ALTER TABLE "donations"
  ADD CONSTRAINT "donations_status_timestamps_check"
    CHECK (
      ("status" = 'PENDING' AND "confirmedAt" IS NULL AND "cancelledAt" IS NULL)
      OR ("status" = 'COMPLETED' AND "confirmedAt" IS NOT NULL AND "cancelledAt" IS NULL)
      OR ("status" = 'CANCELLED' AND "confirmedAt" IS NULL AND "cancelledAt" IS NOT NULL)
    );

ALTER TABLE "campaign_participants"
  ADD CONSTRAINT "campaign_participants_timestamps_check"
    CHECK (
      "cancelledAt" IS NULL
      OR "confirmedAt" IS NULL
      OR "cancelledAt" >= "confirmedAt"
    );

-- These indexes duplicate the single-column unique indexes generated by @unique.
DROP INDEX "campaign_accountabilities_campaignId_idx";
DROP INDEX "organizer_profiles_cnpj_idx";

COMMENT ON CONSTRAINT "campaigns_end_date_after_start_date_check" ON "campaigns"
  IS 'Campaigns must end after they start.';
COMMENT ON CONSTRAINT "campaigns_physical_fields_check" ON "campaigns"
  IS 'Physical campaigns require location and nonnegative item tracking and cannot carry virtual payment fields.';
COMMENT ON CONSTRAINT "campaigns_virtual_fields_check" ON "campaigns"
  IS 'Virtual campaigns require at least one payment method and cannot carry physical item fields.';
COMMENT ON CONSTRAINT "campaigns_lifecycle_timestamps_check" ON "campaigns"
  IS 'Campaign lifecycle status determines which terminal timestamp may be set.';
COMMENT ON CONSTRAINT "campaign_accountabilities_total_items_nonnegative_check" ON "campaign_accountabilities"
  IS 'Accountability totals cannot be negative.';
COMMENT ON CONSTRAINT "organizer_profiles_type_cnpj_check" ON "organizer_profiles"
  IS 'Organizations require a normalized CNPJ; individuals cannot have or verify one.';
COMMENT ON CONSTRAINT "donations_status_timestamps_check" ON "donations"
  IS 'Donation status determines whether confirmation or cancellation timestamp is allowed.';
COMMENT ON CONSTRAINT "campaign_participants_timestamps_check" ON "campaign_participants"
  IS 'A participation cancellation cannot precede an existing confirmation timestamp.';

COMMIT;
